version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: ClusterDEIUserGuide-master/docs/conf.py

python:
  install:
    - requirements: ClusterDEIUserGuide-master/docs/requirements.txt
